services:
  wordpress:
    container_name: bk-wordpress
    image: wordpress:5.2-php7.3-apache
    ports:
      - '80:80'
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=best_user
      - WORDPRESS_DB_PASSWORD=best_pass
      - WORDPRESS_DB_NAME=best_db
    volumes:
      - ./files:/var/www/html
    depends_on:
      - db
  db:
    container_name: bk-db
    image: mariadb:5.5
    environment:
      - MYSQL_USER=best_user
      - MYSQL_PASSWORD=best_pass
      - MYSQL_DATABASE=best_db
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./dbdata:/var/lib/mysql

  phpmyadmin:
    container_name: bk-phpmyadmin
    image: phpmyadmin:5.1-apache
    environment:
      - PMA_HOST=db
      - PMA_USER=best_user
      - PMA_PASSWORD=best_pass
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '8050:80'
    depends_on:
      - db
